In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
import pandas as pd

df = pd.read_csv(r"C:\Users\hp\OneDrive\Documents\OIBSIP\DataAnalytics-L1\Task3_Data_Cleaning\hotel_bookings.csv")

df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03


## Dataset Information

This dataset contains hotel booking records with information about customers, booking details, stay duration, and reservation status. The dataset includes both numerical and categorical features that require data quality assessment before analysis.

In [4]:
print("Shape of the dataset:", df.shape)
print("\nDataset Information:")
df.info()

Shape of the dataset: (119390, 32)

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119386 non-null  float64
 11  babies               

### Observation

- The dataset contains **119,390 rows** and **32 columns**.
- It includes **16 integer columns, 4 float columns, and 12 object (categorical) columns**.
- Missing values are present in the `children`, `country`, `agent`, and `company` columns.
- The `reservation_status_date` column is stored as an object and should be converted to a datetime format.
- Most columns have complete records, making the dataset suitable for further cleaning and analysis.

## Statistical Summary

The statistical summary provides key descriptive statistics such as count, mean, standard deviation, minimum, maximum, and quartiles for numerical columns. It helps identify unusual values and potential outliers that may require further investigation.

In [5]:
df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000


In [6]:
missing_values = df.isnull().sum()
missing_values[missing_values > 0]

children         4
country        488
agent        16340
company     112593
dtype: int64

In [7]:
duplicates = df.duplicated().sum()
print("Number of duplicate rows:", duplicates)

Number of duplicate rows: 31994


In [8]:
df.dtypes

hotel                              object
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                             

## Data Type Inspection

The dataset contains integer, float, and object data types. The `reservation_status_date` column is stored as an object and should be converted to a datetime format during data cleaning.

In [9]:
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company         

## Missing Value Handling

- `children`: Missing values were replaced with the median because it is a numerical column and the median is robust to outliers.
- `country`: Missing values were filled with the most frequent country (mode) because it is a categorical feature.
- `agent` and `company`: Missing values were replaced with `0` to indicate that no travel agent or company was associated with the booking.

In [14]:
# Fill missing values in 'children' with the median
df['children'] = df['children'].fillna(df['children'].median())

# Fill missing values in 'country' with the mode
df['country'] = df['country'].fillna(df['country'].mode()[0])

# Fill missing values in 'agent' with 0
df['agent'] = df['agent'].fillna(0)

# Fill missing values in 'company' with 0
df['company'] = df['company'].fillna(0)

In [15]:
df.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                         

## Missing Value Handling

The missing values were handled using different strategies based on the type and meaning of each column:

- `children`: Missing values were replaced with the median because it is a numerical column and the median is less affected by outliers.
- `country`: Missing values were filled with the most frequent value (mode) since it is a categorical feature.
- `agent`: Missing values were replaced with `0`, indicating that no travel agent was associated with the booking.
- `company`: Missing values were replaced with `0`, indicating that no company booking was associated with the reservation.

After applying these techniques, the dataset contains no missing values.

In [16]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows before removal:", duplicate_count)

Duplicate rows before removal: 32013


In [17]:
df = df.drop_duplicates()

In [18]:
print("Duplicate rows after removal:", df.duplicated().sum())

Duplicate rows after removal: 0


In [19]:
print("New dataset shape:", df.shape)

New dataset shape: (87377, 32)


## Duplicate Row Removal

The dataset was checked for duplicate records using the `duplicated()` function.

A total of **31,994 duplicate rows** were identified and removed to eliminate redundant information and improve data quality.

After removing duplicates, the dataset contains only unique booking records, making it more reliable for further analysis.

In [20]:
# Remove leading/trailing spaces from object columns
object_columns = df.select_dtypes(include='object').columns

for col in object_columns:
    df[col] = df[col].str.strip()

In [21]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,0.0,0.0,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,0.0,0.0,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,0.0,0.0,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,0.0,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,0.0,0,Transient,98.0,0,1,Check-Out,2015-07-03


## Data Standardization

Text columns were standardized by removing unnecessary leading and trailing spaces. This ensures consistency across categorical variables and improves data quality for future analysis.

In [22]:
df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'])

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87377 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype         
---  ------                          --------------  -----         
 0   hotel                           87377 non-null  object        
 1   is_canceled                     87377 non-null  int64         
 2   lead_time                       87377 non-null  int64         
 3   arrival_date_year               87377 non-null  int64         
 4   arrival_date_month              87377 non-null  object        
 5   arrival_date_week_number        87377 non-null  int64         
 6   arrival_date_day_of_month       87377 non-null  int64         
 7   stays_in_weekend_nights         87377 non-null  int64         
 8   stays_in_week_nights            87377 non-null  int64         
 9   adults                          87377 non-null  int64         
 10  children                        87377 non-null  float64       
 11  babies

## Data Type Correction

The `reservation_status_date` column was converted from an object data type to `datetime` to enable efficient date-based analysis and ensure correct data representation.

In [24]:
# Select numerical columns
numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns

for col in numerical_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = ((df[col] < lower) | (df[col] > upper)).sum()

    print(f"{col}: {outliers} outliers")

is_canceled: 0 outliers
lead_time: 2396 outliers
arrival_date_year: 0 outliers
arrival_date_week_number: 0 outliers
arrival_date_day_of_month: 0 outliers
stays_in_weekend_nights: 220 outliers
stays_in_week_nights: 1531 outliers
adults: 22887 outliers
children: 8364 outliers
babies: 914 outliers
is_repeated_guest: 3415 outliers
previous_cancellations: 1685 outliers
previous_bookings_not_canceled: 3545 outliers
booking_changes: 15901 outliers
agent: 0 outliers
company: 5255 outliers
days_in_waiting_list: 860 outliers
adr: 2488 outliers
required_car_parking_spaces: 7313 outliers
total_of_special_requests: 2672 outliers


## Outlier Detection

The Interquartile Range (IQR) method was used to identify outliers in all numerical columns.

Outliers were detected in features such as `lead_time`, `adr`, `booking_changes`, and `adults`.

After careful evaluation, these outliers were **retained** because they represent genuine hotel booking scenarios (e.g., long booking lead times, premium room prices, or large group bookings) rather than data entry errors.

Retaining these values preserves valuable business information and ensures that meaningful observations are not removed from the dataset.

In [25]:
summary = pd.DataFrame({
    "Metric": ["Rows", "Columns", "Missing Values", "Duplicate Rows"],
    "Before Cleaning": [119390, 32, 129425, 31994],
    "After Cleaning": [
        df.shape[0],
        df.shape[1],
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ]
})

summary

,Metric,Before Cleaning,After Cleaning
0,Rows,119390,87377
1,Columns,32,32
2,Missing Values,129425,0
3,Duplicate Rows,31994,0


In [26]:
df.to_csv("cleaned_hotel_bookings.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!


## Conclusion

The Hotel Booking Demand dataset was successfully cleaned and prepared for analysis.

### Cleaning Summary
- Missing values were handled using appropriate imputation techniques.
- Duplicate records were identified and removed.
- Text columns were standardized by removing unnecessary spaces.
- The `reservation_status_date` column was converted to the `datetime` data type.
- Outliers were identified using the IQR method and retained after evaluating their business relevance.
- The cleaned dataset was saved as a new CSV file for future analysis.

The final dataset is complete, consistent, and ready for exploratory data analysis and machine learning tasks.